<?php
@define('CUSTOM_FIELDS_URLPATH',__(plugin_dir_url( __FILE__ ),DOMAIN));
@define('SELECT_ALL',__('Select all',DOMAIN));
@define('CATEGORY_MSG',__('Select listing category from here. Select atleast one category',DOMAIN));
@define('GET_MAP_MSG',__('Click on "Set Address on Map" and then you can also drag pinpoint to locate the correct address',DOMAIN));
@define('PRO_SUBMIT_BUTTON',__('Pay &amp; Publish',DOMAIN));
@define('PUBLISH_BUTTON',__('Submit',DOMAIN));
@define('PRO_UPDATE_BUTTON',__('Update Now',DOMAIN));
@define('MORE_PHOTOS',__('More Photos of',DOMAIN));
@define('POST_DETAIL',__('Your submitted Information',DOMAIN));
@define('POST_SUCCESS_MSG',__('<p class="sucess_msg_prop">Thank you for listing your post with us. We have received your post request successfully.</p>[#submited_information_link#]',DOMAIN));
@define('POST_UPDATED_MSG',__('<p class="sucess_msg_prop">Thank you for listing your post at our site, your post request has been updated successfully.</p>[#submited_information_link#]<p></p>',DOMAIN));
@define('SUBMIT_BUTTON',__('Submit',DOMAIN));
@define('SUBMIT_POST_TEXT',__('Submit a post',DOMAIN));
@define('COUPON_CODE_TITLE_TEXT',__('Coupon Code',DOMAIN));
@define('PREVIEW_BUTTON_TEXT',__('Preview This Post',DOMAIN));
@define('NEXT_STEP',__('Next step',DOMAIN));
@define('PRO_PREVIEW_CANCEL_BUTTON',__('Cancel',DOMAIN));
@define('POSTED_SUCCESS_TITLE',__('Posted Successfully Information',DOMAIN));
@define('RENEW_SUCCESS_TITLE',__('Renew Successfully Information',DOMAIN));
@define('FIELD_REQUIRED_TEXT',__('required',DOMAIN));
@define('SEARCH_WEBSITE',__('Search this website',DOMAIN));
@define('SEARCH',__('Search',DOMAIN));
@define('CATEGORY',__('Category',DOMAIN));
@define('SELECT_CATEGORY',__('select category',DOMAIN));
@define('DATE_TEXT',__('Date',DOMAIN));
@define('TO',__('<span>to</span>',DOMAIN));
@define('AUTHOR_TEXT',__('Author',DOMAIN));
@define('EXACT_AUTHOR_TEXT',__('Exact author',DOMAIN));
@define('SEARCH_ALERT_MSG',__('Please enter word you want to search',DOMAIN));
@define('TAG_SEARCG_TEXT',__('Tags ',DOMAIN));
@define('POST_POSTED_SUCCESS_PREBANK_MSG','<p>'.__("Thank you! We have successfully received your PreBank payment request.",DOMAIN).'</p><p>'.__("To complete the transaction please transfer ",DOMAIN).' <b>[#payable_amt#] </b> '.__("to our bank account. Our bank details are below.",DOMAIN).'</p><p>'.__("Bank Name:",DOMAIN).' <b>[#bank_name#]</b></p><p>'.__("Account Number:",DOMAIN).' <b>[#account_number#]</b></p><p>'.__("Please include the following number as reference:",DOMAIN).'#[#submition_Id#]</p><p>[#submited_information_link#] </p><p>'.__("Thank you!",DOMAIN).'<br/>[#site_name#].</p>');
@define('PRO_DELETE_PRE_MSG',__('Are you really sure want to DELETE this post? Deleted post can not be recovered later',DOMAIN));
@define('PRO_DELETE_BUTTON',__('Yes, Delete Please!',DOMAIN));
@define('FEATURED_LISTING_LABEL',__('Feature Listing',DOMAIN));
@define('SET_ALIVE_DAYS_LABEL',__('Alive Days',DOMAIN));
@define('SET_ALIVE_DAYS_DESC',__('will be visible on your site for the here mentioned alive days after it gets published.',DOMAIN));

@define('SELECT_PAY_MEHTOD_TEXT',__('Select Payment Method',DOMAIN));
?>