<?php
define('USERNAME_TEXT',__('User name',DOMAIN));
define('PERSONAL_INFO_TEXT',__('Personal Information',DOMAIN));
define('FIRST_NAME_TEXT',__('Full Name',DOMAIN));
define('REGISTRATION_MESSAGE',__('(Note: A password will be e-mailed to you for future reference.)',DOMAIN));
define('EDIT_PROFILE_PAGE_TITLE',__('Edit profile',DOMAIN));
define('FACEBOOK_TEXT',__('Facebook link',DOMAIN));
define('PASSWORD_TEXT',__('Password',DOMAIN));
define('FORGOT_PW_TEXT',__('Forgot password',DOMAIN));
define('PRO_CANCEL_BUTTON',__('Cancel',DOMAIN));
define('TWITTER_TEXT',__('Twitter link',DOMAIN));
define('CHANGE_PW_TEXT',__('Change password',DOMAIN));
define('REGISTER_BUTTON',__('Register',DOMAIN));
define('DASHBOARD_TEXT',__('Dashboard',DOMAIN));
define('LOGOUT_TEXT',__('Logout',DOMAIN));
define('SIGN_IN_PAGE_TITLE',__('Sign In',DOMAIN));
define('INVALID_USER_PW_MSG',__('Invalid Username/Password.',DOMAIN));
define('REG_COMPLETE_MSG',__('Registration complete. Please check your e-mail for login details.',DOMAIN));
define('NEW_PW_EMAIL_MSG',__('We just sent you a new password. Kindly check your e-mail now.',DOMAIN));
define('EMAIL_CONFIRM_LINK_MSG',__('A confirmation link has been sent to you via email. Kindly check your e-mail now.',DOMAIN));
define('USER_REG_NOT_ALLOW_MSG',__('User registration has been disabled by the admin.',DOMAIN));
define('YOU_ARE_LOGED_OUT_MSG',__('You are now logged out.',DOMAIN));
define('ENTER_USER_EMAIL_NEW_PW_MSG',__('Please enter your e-mail address as username. You will receive a new password via e-mail.',DOMAIN));
define('INVALID_USER_FPW_MSG',__('Invalid Email, please check',DOMAIN));
define('PW_SEND_CONFIRM_MSG',__('Check your e-mail for your new password.',DOMAIN));
define('REGISTRATION_SUCCESS_MSG',__('Thank you for registration! Please check your mail to get your login information.',DOMAIN));
define('REGISTRATION_ACTIVATION_MSG',__('Your account has been activated successfully, your login details has been sent to your email id.',DOMAIN));
define('INVALIDCAPTCHA',__('Invalid Captcha.',DOMAIN));
define('INVALIDPLAY',__('Please play the game to register.',DOMAIN));
//profile.php
define('EDIT_PROFILE_TITLE',__('Edit Profile',DOMAIN));
define('CONFIRM_PASSWORD_TEXT',__('Confirm Password',DOMAIN));
define('EDIT_BUTTON',__('Edit',DOMAIN));
define('EDIT_PROFILE_SUCCESS_MSG',__('Profile edited successfully.',DOMAIN));
define('EMPTY_EMAIL_MSG',__('Please enter Email.',DOMAIN));
define('ALREADY_EXIST_MSG',__('Email already exists, please choose another.',DOMAIN));
define('PW_NO_MATCH_MSG',__('Password and Confirm Password should same.',DOMAIN));
define('SIGN_IN_USING_SOCIAL_PROFILE',__('Sign in using social profile',DOMAIN));
define('PROFILE_EDIT_TEXT',__('Edit Profile',DOMAIN));
define('PLEASE_SELECT',__('Please select',DOMAIN));
?>